#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from Maindialog.ui on Sat Feb  6 19:41:04 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(686, 445)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 511, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.basedir = KLineEdit(self.verticalLayoutWidget)
        self.basedir.setObjectName("basedir")
        self.verticalLayout.addWidget(self.basedir)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.output = KTextEdit(self.verticalLayoutWidget)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kpushbutton_2 = KPushButton(self.verticalLayoutWidget)
        self.kpushbutton_2.setObjectName("kpushbutton_2")
        self.horizontalLayout.addWidget(self.kpushbutton_2)
        self.dryrunButton = KPushButton(self.verticalLayoutWidget)
        self.dryrunButton.setObjectName("dryrunButton")
        self.horizontalLayout.addWidget(self.dryrunButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Genre Tagger"))
        self.label.setText(kdecore.i18n("Basedir"))
        self.label_2.setText(kdecore.i18n("Output"))
        self.dryrunButton.setText(kdecore.i18n("Dry run"))

from PyKDE4.kdeui import KDialog, KPushButton, KTextEdit, KLineEdit
